# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"

env:
  global:
    - PERL5LIB=${TRAVIS_BUILD_DIR}/perl5
    - CIRCOS_VERSION=0.69-2
    - CIRCOS_PKG=circos-${CIRCOS_VERSION}.tgz
    - CIRCOS_URL=http://circos.ca/distribution/${CIRCOS_PKG}

before_install:

    # Install Circos manually
    - sudo apt-get install cpanminus libgd-dev
    - cpanm --local-lib=${TRAVIS_BUILD_DIR}/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
    - cpanm --notest Clone Config::General Cwd Data::Dumper Digest::MD5 File::Basename File::Spec::Functions File::Temp FindBin Font::TTF::Font GD GD::Polyline Getopt::Long IO::File List::MoreUtils List::Util Math::Bezier Math::BigFloat Math::Round Math::VecStat Memoize POSIX Params::Validate Pod::Usage Readonly Regexp::Common SVG Set::IntSpan Statistics::Basic Storable Sys::Hostname Text::Balanced Text::Format Time::HiRes
    - wget ${CIRCOS_URL} && tar xvf ${CIRCOS_PKG} && sudo ln -s ${TRAVIS_BUILD_DIR}/${CIRCOS_VERSION}/bin/* /usr/bin/local/

    # Install test dependencies
    - pip install -r requirements-dev.txt

install:
    - python setup.py install
    - pip install coveralls --use-wheel

script:
    - py.test -v --flake8 fsnviz/
